---
# tasks file for imbicile.nano
- name: install nano
  apt:
    pkg:
      - nano
      - zip
      - unzip
    update_cache: yes
    state: latest

- name: download nano-highlight
  get_url:
    url: "{{ git_repo }}"
    dest: "/tmp/nanorc.zip"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: unarchive nanorc
  unarchive:
    src: "/tmp/nanorc.zip"
    dest: "/tmp"
    mode: 0755
    remote_src: yes

- name: get nanorc files
  shell: |
    ls /tmp/nanorc-master/*.nanorc
  register: nanorc_files
  changed_when: false
  failed_when: false

- name: copy nanorc
  copy:
    src: "{{ item }}"
    dest: "/usr/share/nano"
    mode: 0644
    owner: root
    group: root
    remote_src: yes
  with_items: "{{ nanorc_files.stdout_lines }}"

- name: create conf
  template:
    src: "nanorc.j2"
    dest: "/etc/nanorc"
    mode: 0644
    owner: root
    group: root
